### ISSUE TITLE
Backport Bulk API to 2.2

### ISSUE THREAD

**Issue by vrann** [magento/bulk-api-ce#18]
There are a lot of current merchants on 2.2 who were interested of using Bulk API
As long as Message Queue was on available in 2.2, it will work on EE only

**Comment by nuzil** [comment]
PRs are ready
Now I see that tests are failed, next step: fix them

**Comment by cmuench** [comment]
We (netz98) are very interested in using the BulkAPI for a product. Maybe we can act as beta tester or help to improve the API.
