### ISSUE TITLE
Create Performance Test for the Bulk API

### ISSUE THREAD

**Issue by vrann** [magento/bulk-api-ce#19]
We need to establish baseline of the Bulk API performance measurements so that it can be improved over time
Measure: 
- average response time with the number of concurrent requests (1K, 2K, etc)
-- for Synchronous case
-- for Asynchronous case
-- for Redis storage
- number of concurrent workers which can process the message queue
- average time concurrent workers can process 1K, 2K ,100K of messages with certain operation

**Comment by nuzil** [comment]
Moved to Async
