### ISSUE TITLE
Cron run failure on default installation

### ISSUE THREAD

**Issue by vkublytskyi** [magento/bulk-api-ce#28]
## Precondition
Magento downloaded from https://github.com/magento/magento2ce.git and https://github.com/magento/magento2ee.git

## Steps to reproduce:

1. Install latest develop Magento EE from GitHub.
1. Do `bin/magento cron:run`

## Expected result
Run jobs by schedule. No additional message is present.

## Actual result
Run jobs by schedule.

```
[LogicException] 
Unknown connection name amqp 
queue:consumers:start [--max-messages MAX-MESSAGES] [--batch-size BATCH-SIZE] [--area-code AREA-CODE] [--pid-file-path PID-FILE-PATH] [--] <consumer>
```

### Affected versions

Issue present in 2.2 and 2.3

### Notes

If change [queue_consumer](https://github.com/magento/magento2ee/blob/6f5b9d3e423dc30f93568d850beeb5836d023397/app/code/Magento/WebapiAsync/etc/queue_consumer.xml#L10) and [queue_topology] to db no errors after running cron, but appear new error after uninstall

![error.jpg](https://images.zenhubusercontent.com/5a674fb54b5806bc2bc3f230/dc44aa3b-87ce-4f44-a786-6efe71fd26f0)

**Comment by anvasiliev** [comment]
PR with fix https://github.com/magento/bulk-api-ce/pull/29
